---

version: "3.7"

services:
  app:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION_TAG=${NODE_VERSION_TAG}
    volumes:
      - ./:/app
